# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/cyip022/final/repo/final-project-jbour009-cyip022-dpham125-ahuan190

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/cyip022/final/repo/final-project-jbour009-cyip022-dpham125-ahuan190

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/cyip022/final/repo/final-project-jbour009-cyip022-dpham125-ahuan190/CMakeFiles /home/csmajs/cyip022/final/repo/final-project-jbour009-cyip022-dpham125-ahuan190//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/cyip022/final/repo/final-project-jbour009-cyip022-dpham125-ahuan190/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named allBiomeTests

# Build rule for target.
allBiomeTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 allBiomeTests
.PHONY : allBiomeTests

# fast build rule for target.
allBiomeTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/build
.PHONY : allBiomeTests/fast

#=============================================================================
# Target rules for targets named allDisplayTests

# Build rule for target.
allDisplayTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 allDisplayTests
.PHONY : allDisplayTests

# fast build rule for target.
allDisplayTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allDisplayTests.dir/build.make CMakeFiles/allDisplayTests.dir/build
.PHONY : allDisplayTests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

Biomes/DesertOfDeath.o: Biomes/DesertOfDeath.cpp.o
.PHONY : Biomes/DesertOfDeath.o

# target to build an object file
Biomes/DesertOfDeath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/DesertOfDeath.cpp.o
.PHONY : Biomes/DesertOfDeath.cpp.o

Biomes/DesertOfDeath.i: Biomes/DesertOfDeath.cpp.i
.PHONY : Biomes/DesertOfDeath.i

# target to preprocess a source file
Biomes/DesertOfDeath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/DesertOfDeath.cpp.i
.PHONY : Biomes/DesertOfDeath.cpp.i

Biomes/DesertOfDeath.s: Biomes/DesertOfDeath.cpp.s
.PHONY : Biomes/DesertOfDeath.s

# target to generate assembly for a file
Biomes/DesertOfDeath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/DesertOfDeath.cpp.s
.PHONY : Biomes/DesertOfDeath.cpp.s

Biomes/KingsLand.o: Biomes/KingsLand.cpp.o
.PHONY : Biomes/KingsLand.o

# target to build an object file
Biomes/KingsLand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/KingsLand.cpp.o
.PHONY : Biomes/KingsLand.cpp.o

Biomes/KingsLand.i: Biomes/KingsLand.cpp.i
.PHONY : Biomes/KingsLand.i

# target to preprocess a source file
Biomes/KingsLand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/KingsLand.cpp.i
.PHONY : Biomes/KingsLand.cpp.i

Biomes/KingsLand.s: Biomes/KingsLand.cpp.s
.PHONY : Biomes/KingsLand.s

# target to generate assembly for a file
Biomes/KingsLand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/KingsLand.cpp.s
.PHONY : Biomes/KingsLand.cpp.s

Biomes/Pathways.o: Biomes/Pathways.cpp.o
.PHONY : Biomes/Pathways.o

# target to build an object file
Biomes/Pathways.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/Pathways.cpp.o
.PHONY : Biomes/Pathways.cpp.o

Biomes/Pathways.i: Biomes/Pathways.cpp.i
.PHONY : Biomes/Pathways.i

# target to preprocess a source file
Biomes/Pathways.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/Pathways.cpp.i
.PHONY : Biomes/Pathways.cpp.i

Biomes/Pathways.s: Biomes/Pathways.cpp.s
.PHONY : Biomes/Pathways.s

# target to generate assembly for a file
Biomes/Pathways.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/Pathways.cpp.s
.PHONY : Biomes/Pathways.cpp.s

Biomes/StarterForest.o: Biomes/StarterForest.cpp.o
.PHONY : Biomes/StarterForest.o

# target to build an object file
Biomes/StarterForest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/StarterForest.cpp.o
.PHONY : Biomes/StarterForest.cpp.o

Biomes/StarterForest.i: Biomes/StarterForest.cpp.i
.PHONY : Biomes/StarterForest.i

# target to preprocess a source file
Biomes/StarterForest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/StarterForest.cpp.i
.PHONY : Biomes/StarterForest.cpp.i

Biomes/StarterForest.s: Biomes/StarterForest.cpp.s
.PHONY : Biomes/StarterForest.s

# target to generate assembly for a file
Biomes/StarterForest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/StarterForest.cpp.s
.PHONY : Biomes/StarterForest.cpp.s

Biomes/TremorousCaves.o: Biomes/TremorousCaves.cpp.o
.PHONY : Biomes/TremorousCaves.o

# target to build an object file
Biomes/TremorousCaves.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/TremorousCaves.cpp.o
.PHONY : Biomes/TremorousCaves.cpp.o

Biomes/TremorousCaves.i: Biomes/TremorousCaves.cpp.i
.PHONY : Biomes/TremorousCaves.i

# target to preprocess a source file
Biomes/TremorousCaves.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/TremorousCaves.cpp.i
.PHONY : Biomes/TremorousCaves.cpp.i

Biomes/TremorousCaves.s: Biomes/TremorousCaves.cpp.s
.PHONY : Biomes/TremorousCaves.s

# target to generate assembly for a file
Biomes/TremorousCaves.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/TremorousCaves.cpp.s
.PHONY : Biomes/TremorousCaves.cpp.s

Biomes/shop.o: Biomes/shop.cpp.o
.PHONY : Biomes/shop.o

# target to build an object file
Biomes/shop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/shop.cpp.o
.PHONY : Biomes/shop.cpp.o

Biomes/shop.i: Biomes/shop.cpp.i
.PHONY : Biomes/shop.i

# target to preprocess a source file
Biomes/shop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/shop.cpp.i
.PHONY : Biomes/shop.cpp.i

Biomes/shop.s: Biomes/shop.cpp.s
.PHONY : Biomes/shop.s

# target to generate assembly for a file
Biomes/shop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Biomes/shop.cpp.s
.PHONY : Biomes/shop.cpp.s

Player/Inventory.o: Player/Inventory.cpp.o
.PHONY : Player/Inventory.o

# target to build an object file
Player/Inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Player/Inventory.cpp.o
.PHONY : Player/Inventory.cpp.o

Player/Inventory.i: Player/Inventory.cpp.i
.PHONY : Player/Inventory.i

# target to preprocess a source file
Player/Inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Player/Inventory.cpp.i
.PHONY : Player/Inventory.cpp.i

Player/Inventory.s: Player/Inventory.cpp.s
.PHONY : Player/Inventory.s

# target to generate assembly for a file
Player/Inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Player/Inventory.cpp.s
.PHONY : Player/Inventory.cpp.s

Player/Player.o: Player/Player.cpp.o
.PHONY : Player/Player.o

# target to build an object file
Player/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Player/Player.cpp.o
.PHONY : Player/Player.cpp.o

Player/Player.i: Player/Player.cpp.i
.PHONY : Player/Player.i

# target to preprocess a source file
Player/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Player/Player.cpp.i
.PHONY : Player/Player.cpp.i

Player/Player.s: Player/Player.cpp.s
.PHONY : Player/Player.s

# target to generate assembly for a file
Player/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/Player/Player.cpp.s
.PHONY : Player/Player.cpp.s

ScreenDisplay/src/Hotbar.o: ScreenDisplay/src/Hotbar.cpp.o
.PHONY : ScreenDisplay/src/Hotbar.o

# target to build an object file
ScreenDisplay/src/Hotbar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allDisplayTests.dir/build.make CMakeFiles/allDisplayTests.dir/ScreenDisplay/src/Hotbar.cpp.o
.PHONY : ScreenDisplay/src/Hotbar.cpp.o

ScreenDisplay/src/Hotbar.i: ScreenDisplay/src/Hotbar.cpp.i
.PHONY : ScreenDisplay/src/Hotbar.i

# target to preprocess a source file
ScreenDisplay/src/Hotbar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allDisplayTests.dir/build.make CMakeFiles/allDisplayTests.dir/ScreenDisplay/src/Hotbar.cpp.i
.PHONY : ScreenDisplay/src/Hotbar.cpp.i

ScreenDisplay/src/Hotbar.s: ScreenDisplay/src/Hotbar.cpp.s
.PHONY : ScreenDisplay/src/Hotbar.s

# target to generate assembly for a file
ScreenDisplay/src/Hotbar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allDisplayTests.dir/build.make CMakeFiles/allDisplayTests.dir/ScreenDisplay/src/Hotbar.cpp.s
.PHONY : ScreenDisplay/src/Hotbar.cpp.s

ScreenDisplay/src/ReadScreenFile.o: ScreenDisplay/src/ReadScreenFile.cpp.o
.PHONY : ScreenDisplay/src/ReadScreenFile.o

# target to build an object file
ScreenDisplay/src/ReadScreenFile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allDisplayTests.dir/build.make CMakeFiles/allDisplayTests.dir/ScreenDisplay/src/ReadScreenFile.cpp.o
.PHONY : ScreenDisplay/src/ReadScreenFile.cpp.o

ScreenDisplay/src/ReadScreenFile.i: ScreenDisplay/src/ReadScreenFile.cpp.i
.PHONY : ScreenDisplay/src/ReadScreenFile.i

# target to preprocess a source file
ScreenDisplay/src/ReadScreenFile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allDisplayTests.dir/build.make CMakeFiles/allDisplayTests.dir/ScreenDisplay/src/ReadScreenFile.cpp.i
.PHONY : ScreenDisplay/src/ReadScreenFile.cpp.i

ScreenDisplay/src/ReadScreenFile.s: ScreenDisplay/src/ReadScreenFile.cpp.s
.PHONY : ScreenDisplay/src/ReadScreenFile.s

# target to generate assembly for a file
ScreenDisplay/src/ReadScreenFile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allDisplayTests.dir/build.make CMakeFiles/allDisplayTests.dir/ScreenDisplay/src/ReadScreenFile.cpp.s
.PHONY : ScreenDisplay/src/ReadScreenFile.cpp.s

ScreenDisplay/src/ScreenDisplay.o: ScreenDisplay/src/ScreenDisplay.cpp.o
.PHONY : ScreenDisplay/src/ScreenDisplay.o

# target to build an object file
ScreenDisplay/src/ScreenDisplay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allDisplayTests.dir/build.make CMakeFiles/allDisplayTests.dir/ScreenDisplay/src/ScreenDisplay.cpp.o
.PHONY : ScreenDisplay/src/ScreenDisplay.cpp.o

ScreenDisplay/src/ScreenDisplay.i: ScreenDisplay/src/ScreenDisplay.cpp.i
.PHONY : ScreenDisplay/src/ScreenDisplay.i

# target to preprocess a source file
ScreenDisplay/src/ScreenDisplay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allDisplayTests.dir/build.make CMakeFiles/allDisplayTests.dir/ScreenDisplay/src/ScreenDisplay.cpp.i
.PHONY : ScreenDisplay/src/ScreenDisplay.cpp.i

ScreenDisplay/src/ScreenDisplay.s: ScreenDisplay/src/ScreenDisplay.cpp.s
.PHONY : ScreenDisplay/src/ScreenDisplay.s

# target to generate assembly for a file
ScreenDisplay/src/ScreenDisplay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allDisplayTests.dir/build.make CMakeFiles/allDisplayTests.dir/ScreenDisplay/src/ScreenDisplay.cpp.s
.PHONY : ScreenDisplay/src/ScreenDisplay.cpp.s

ScreenDisplay/test/test.o: ScreenDisplay/test/test.cpp.o
.PHONY : ScreenDisplay/test/test.o

# target to build an object file
ScreenDisplay/test/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allDisplayTests.dir/build.make CMakeFiles/allDisplayTests.dir/ScreenDisplay/test/test.cpp.o
.PHONY : ScreenDisplay/test/test.cpp.o

ScreenDisplay/test/test.i: ScreenDisplay/test/test.cpp.i
.PHONY : ScreenDisplay/test/test.i

# target to preprocess a source file
ScreenDisplay/test/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allDisplayTests.dir/build.make CMakeFiles/allDisplayTests.dir/ScreenDisplay/test/test.cpp.i
.PHONY : ScreenDisplay/test/test.cpp.i

ScreenDisplay/test/test.s: ScreenDisplay/test/test.cpp.s
.PHONY : ScreenDisplay/test/test.s

# target to generate assembly for a file
ScreenDisplay/test/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allDisplayTests.dir/build.make CMakeFiles/allDisplayTests.dir/ScreenDisplay/test/test.cpp.s
.PHONY : ScreenDisplay/test/test.cpp.s

combatCMake/combatSrc/cabinspirit.o: combatCMake/combatSrc/cabinspirit.cpp.o
.PHONY : combatCMake/combatSrc/cabinspirit.o

# target to build an object file
combatCMake/combatSrc/cabinspirit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/cabinspirit.cpp.o
.PHONY : combatCMake/combatSrc/cabinspirit.cpp.o

combatCMake/combatSrc/cabinspirit.i: combatCMake/combatSrc/cabinspirit.cpp.i
.PHONY : combatCMake/combatSrc/cabinspirit.i

# target to preprocess a source file
combatCMake/combatSrc/cabinspirit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/cabinspirit.cpp.i
.PHONY : combatCMake/combatSrc/cabinspirit.cpp.i

combatCMake/combatSrc/cabinspirit.s: combatCMake/combatSrc/cabinspirit.cpp.s
.PHONY : combatCMake/combatSrc/cabinspirit.s

# target to generate assembly for a file
combatCMake/combatSrc/cabinspirit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/cabinspirit.cpp.s
.PHONY : combatCMake/combatSrc/cabinspirit.cpp.s

combatCMake/combatSrc/character.o: combatCMake/combatSrc/character.cpp.o
.PHONY : combatCMake/combatSrc/character.o

# target to build an object file
combatCMake/combatSrc/character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/character.cpp.o
.PHONY : combatCMake/combatSrc/character.cpp.o

combatCMake/combatSrc/character.i: combatCMake/combatSrc/character.cpp.i
.PHONY : combatCMake/combatSrc/character.i

# target to preprocess a source file
combatCMake/combatSrc/character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/character.cpp.i
.PHONY : combatCMake/combatSrc/character.cpp.i

combatCMake/combatSrc/character.s: combatCMake/combatSrc/character.cpp.s
.PHONY : combatCMake/combatSrc/character.s

# target to generate assembly for a file
combatCMake/combatSrc/character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/character.cpp.s
.PHONY : combatCMake/combatSrc/character.cpp.s

combatCMake/combatSrc/crygolem.o: combatCMake/combatSrc/crygolem.cpp.o
.PHONY : combatCMake/combatSrc/crygolem.o

# target to build an object file
combatCMake/combatSrc/crygolem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/crygolem.cpp.o
.PHONY : combatCMake/combatSrc/crygolem.cpp.o

combatCMake/combatSrc/crygolem.i: combatCMake/combatSrc/crygolem.cpp.i
.PHONY : combatCMake/combatSrc/crygolem.i

# target to preprocess a source file
combatCMake/combatSrc/crygolem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/crygolem.cpp.i
.PHONY : combatCMake/combatSrc/crygolem.cpp.i

combatCMake/combatSrc/crygolem.s: combatCMake/combatSrc/crygolem.cpp.s
.PHONY : combatCMake/combatSrc/crygolem.s

# target to generate assembly for a file
combatCMake/combatSrc/crygolem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/crygolem.cpp.s
.PHONY : combatCMake/combatSrc/crygolem.cpp.s

combatCMake/combatSrc/darkgobshaman.o: combatCMake/combatSrc/darkgobshaman.cpp.o
.PHONY : combatCMake/combatSrc/darkgobshaman.o

# target to build an object file
combatCMake/combatSrc/darkgobshaman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/darkgobshaman.cpp.o
.PHONY : combatCMake/combatSrc/darkgobshaman.cpp.o

combatCMake/combatSrc/darkgobshaman.i: combatCMake/combatSrc/darkgobshaman.cpp.i
.PHONY : combatCMake/combatSrc/darkgobshaman.i

# target to preprocess a source file
combatCMake/combatSrc/darkgobshaman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/darkgobshaman.cpp.i
.PHONY : combatCMake/combatSrc/darkgobshaman.cpp.i

combatCMake/combatSrc/darkgobshaman.s: combatCMake/combatSrc/darkgobshaman.cpp.s
.PHONY : combatCMake/combatSrc/darkgobshaman.s

# target to generate assembly for a file
combatCMake/combatSrc/darkgobshaman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/darkgobshaman.cpp.s
.PHONY : combatCMake/combatSrc/darkgobshaman.cpp.s

combatCMake/combatSrc/enemy.o: combatCMake/combatSrc/enemy.cpp.o
.PHONY : combatCMake/combatSrc/enemy.o

# target to build an object file
combatCMake/combatSrc/enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/enemy.cpp.o
.PHONY : combatCMake/combatSrc/enemy.cpp.o

combatCMake/combatSrc/enemy.i: combatCMake/combatSrc/enemy.cpp.i
.PHONY : combatCMake/combatSrc/enemy.i

# target to preprocess a source file
combatCMake/combatSrc/enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/enemy.cpp.i
.PHONY : combatCMake/combatSrc/enemy.cpp.i

combatCMake/combatSrc/enemy.s: combatCMake/combatSrc/enemy.cpp.s
.PHONY : combatCMake/combatSrc/enemy.s

# target to generate assembly for a file
combatCMake/combatSrc/enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/enemy.cpp.s
.PHONY : combatCMake/combatSrc/enemy.cpp.s

combatCMake/combatSrc/gatekeeper.o: combatCMake/combatSrc/gatekeeper.cpp.o
.PHONY : combatCMake/combatSrc/gatekeeper.o

# target to build an object file
combatCMake/combatSrc/gatekeeper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/gatekeeper.cpp.o
.PHONY : combatCMake/combatSrc/gatekeeper.cpp.o

combatCMake/combatSrc/gatekeeper.i: combatCMake/combatSrc/gatekeeper.cpp.i
.PHONY : combatCMake/combatSrc/gatekeeper.i

# target to preprocess a source file
combatCMake/combatSrc/gatekeeper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/gatekeeper.cpp.i
.PHONY : combatCMake/combatSrc/gatekeeper.cpp.i

combatCMake/combatSrc/gatekeeper.s: combatCMake/combatSrc/gatekeeper.cpp.s
.PHONY : combatCMake/combatSrc/gatekeeper.s

# target to generate assembly for a file
combatCMake/combatSrc/gatekeeper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/gatekeeper.cpp.s
.PHONY : combatCMake/combatSrc/gatekeeper.cpp.s

combatCMake/combatSrc/gobgrunt.o: combatCMake/combatSrc/gobgrunt.cpp.o
.PHONY : combatCMake/combatSrc/gobgrunt.o

# target to build an object file
combatCMake/combatSrc/gobgrunt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/gobgrunt.cpp.o
.PHONY : combatCMake/combatSrc/gobgrunt.cpp.o

combatCMake/combatSrc/gobgrunt.i: combatCMake/combatSrc/gobgrunt.cpp.i
.PHONY : combatCMake/combatSrc/gobgrunt.i

# target to preprocess a source file
combatCMake/combatSrc/gobgrunt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/gobgrunt.cpp.i
.PHONY : combatCMake/combatSrc/gobgrunt.cpp.i

combatCMake/combatSrc/gobgrunt.s: combatCMake/combatSrc/gobgrunt.cpp.s
.PHONY : combatCMake/combatSrc/gobgrunt.s

# target to generate assembly for a file
combatCMake/combatSrc/gobgrunt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/gobgrunt.cpp.s
.PHONY : combatCMake/combatSrc/gobgrunt.cpp.s

combatCMake/combatSrc/madking.o: combatCMake/combatSrc/madking.cpp.o
.PHONY : combatCMake/combatSrc/madking.o

# target to build an object file
combatCMake/combatSrc/madking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/madking.cpp.o
.PHONY : combatCMake/combatSrc/madking.cpp.o

combatCMake/combatSrc/madking.i: combatCMake/combatSrc/madking.cpp.i
.PHONY : combatCMake/combatSrc/madking.i

# target to preprocess a source file
combatCMake/combatSrc/madking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/madking.cpp.i
.PHONY : combatCMake/combatSrc/madking.cpp.i

combatCMake/combatSrc/madking.s: combatCMake/combatSrc/madking.cpp.s
.PHONY : combatCMake/combatSrc/madking.s

# target to generate assembly for a file
combatCMake/combatSrc/madking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/madking.cpp.s
.PHONY : combatCMake/combatSrc/madking.cpp.s

combatCMake/combatSrc/oasisguard.o: combatCMake/combatSrc/oasisguard.cpp.o
.PHONY : combatCMake/combatSrc/oasisguard.o

# target to build an object file
combatCMake/combatSrc/oasisguard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/oasisguard.cpp.o
.PHONY : combatCMake/combatSrc/oasisguard.cpp.o

combatCMake/combatSrc/oasisguard.i: combatCMake/combatSrc/oasisguard.cpp.i
.PHONY : combatCMake/combatSrc/oasisguard.i

# target to preprocess a source file
combatCMake/combatSrc/oasisguard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/oasisguard.cpp.i
.PHONY : combatCMake/combatSrc/oasisguard.cpp.i

combatCMake/combatSrc/oasisguard.s: combatCMake/combatSrc/oasisguard.cpp.s
.PHONY : combatCMake/combatSrc/oasisguard.s

# target to generate assembly for a file
combatCMake/combatSrc/oasisguard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/oasisguard.cpp.s
.PHONY : combatCMake/combatSrc/oasisguard.cpp.s

combatCMake/combatSrc/overbat.o: combatCMake/combatSrc/overbat.cpp.o
.PHONY : combatCMake/combatSrc/overbat.o

# target to build an object file
combatCMake/combatSrc/overbat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/overbat.cpp.o
.PHONY : combatCMake/combatSrc/overbat.cpp.o

combatCMake/combatSrc/overbat.i: combatCMake/combatSrc/overbat.cpp.i
.PHONY : combatCMake/combatSrc/overbat.i

# target to preprocess a source file
combatCMake/combatSrc/overbat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/overbat.cpp.i
.PHONY : combatCMake/combatSrc/overbat.cpp.i

combatCMake/combatSrc/overbat.s: combatCMake/combatSrc/overbat.cpp.s
.PHONY : combatCMake/combatSrc/overbat.s

# target to generate assembly for a file
combatCMake/combatSrc/overbat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/overbat.cpp.s
.PHONY : combatCMake/combatSrc/overbat.cpp.s

combatCMake/combatSrc/queenspider.o: combatCMake/combatSrc/queenspider.cpp.o
.PHONY : combatCMake/combatSrc/queenspider.o

# target to build an object file
combatCMake/combatSrc/queenspider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/queenspider.cpp.o
.PHONY : combatCMake/combatSrc/queenspider.cpp.o

combatCMake/combatSrc/queenspider.i: combatCMake/combatSrc/queenspider.cpp.i
.PHONY : combatCMake/combatSrc/queenspider.i

# target to preprocess a source file
combatCMake/combatSrc/queenspider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/queenspider.cpp.i
.PHONY : combatCMake/combatSrc/queenspider.cpp.i

combatCMake/combatSrc/queenspider.s: combatCMake/combatSrc/queenspider.cpp.s
.PHONY : combatCMake/combatSrc/queenspider.s

# target to generate assembly for a file
combatCMake/combatSrc/queenspider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/queenspider.cpp.s
.PHONY : combatCMake/combatSrc/queenspider.cpp.s

combatCMake/combatSrc/sandworm.o: combatCMake/combatSrc/sandworm.cpp.o
.PHONY : combatCMake/combatSrc/sandworm.o

# target to build an object file
combatCMake/combatSrc/sandworm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/sandworm.cpp.o
.PHONY : combatCMake/combatSrc/sandworm.cpp.o

combatCMake/combatSrc/sandworm.i: combatCMake/combatSrc/sandworm.cpp.i
.PHONY : combatCMake/combatSrc/sandworm.i

# target to preprocess a source file
combatCMake/combatSrc/sandworm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/sandworm.cpp.i
.PHONY : combatCMake/combatSrc/sandworm.cpp.i

combatCMake/combatSrc/sandworm.s: combatCMake/combatSrc/sandworm.cpp.s
.PHONY : combatCMake/combatSrc/sandworm.s

# target to generate assembly for a file
combatCMake/combatSrc/sandworm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/sandworm.cpp.s
.PHONY : combatCMake/combatSrc/sandworm.cpp.s

combatCMake/combatSrc/sunkwarden.o: combatCMake/combatSrc/sunkwarden.cpp.o
.PHONY : combatCMake/combatSrc/sunkwarden.o

# target to build an object file
combatCMake/combatSrc/sunkwarden.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/sunkwarden.cpp.o
.PHONY : combatCMake/combatSrc/sunkwarden.cpp.o

combatCMake/combatSrc/sunkwarden.i: combatCMake/combatSrc/sunkwarden.cpp.i
.PHONY : combatCMake/combatSrc/sunkwarden.i

# target to preprocess a source file
combatCMake/combatSrc/sunkwarden.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/sunkwarden.cpp.i
.PHONY : combatCMake/combatSrc/sunkwarden.cpp.i

combatCMake/combatSrc/sunkwarden.s: combatCMake/combatSrc/sunkwarden.cpp.s
.PHONY : combatCMake/combatSrc/sunkwarden.s

# target to generate assembly for a file
combatCMake/combatSrc/sunkwarden.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/sunkwarden.cpp.s
.PHONY : combatCMake/combatSrc/sunkwarden.cpp.s

combatCMake/combatSrc/villcultist.o: combatCMake/combatSrc/villcultist.cpp.o
.PHONY : combatCMake/combatSrc/villcultist.o

# target to build an object file
combatCMake/combatSrc/villcultist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/villcultist.cpp.o
.PHONY : combatCMake/combatSrc/villcultist.cpp.o

combatCMake/combatSrc/villcultist.i: combatCMake/combatSrc/villcultist.cpp.i
.PHONY : combatCMake/combatSrc/villcultist.i

# target to preprocess a source file
combatCMake/combatSrc/villcultist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/villcultist.cpp.i
.PHONY : combatCMake/combatSrc/villcultist.cpp.i

combatCMake/combatSrc/villcultist.s: combatCMake/combatSrc/villcultist.cpp.s
.PHONY : combatCMake/combatSrc/villcultist.s

# target to generate assembly for a file
combatCMake/combatSrc/villcultist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/combatCMake/combatSrc/villcultist.cpp.s
.PHONY : combatCMake/combatSrc/villcultist.cpp.s

test/Biome_test.o: test/Biome_test.cpp.o
.PHONY : test/Biome_test.o

# target to build an object file
test/Biome_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/test/Biome_test.cpp.o
.PHONY : test/Biome_test.cpp.o

test/Biome_test.i: test/Biome_test.cpp.i
.PHONY : test/Biome_test.i

# target to preprocess a source file
test/Biome_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/test/Biome_test.cpp.i
.PHONY : test/Biome_test.cpp.i

test/Biome_test.s: test/Biome_test.cpp.s
.PHONY : test/Biome_test.s

# target to generate assembly for a file
test/Biome_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/allBiomeTests.dir/build.make CMakeFiles/allBiomeTests.dir/test/Biome_test.cpp.s
.PHONY : test/Biome_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... allBiomeTests"
	@echo "... allDisplayTests"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... Biomes/DesertOfDeath.o"
	@echo "... Biomes/DesertOfDeath.i"
	@echo "... Biomes/DesertOfDeath.s"
	@echo "... Biomes/KingsLand.o"
	@echo "... Biomes/KingsLand.i"
	@echo "... Biomes/KingsLand.s"
	@echo "... Biomes/Pathways.o"
	@echo "... Biomes/Pathways.i"
	@echo "... Biomes/Pathways.s"
	@echo "... Biomes/StarterForest.o"
	@echo "... Biomes/StarterForest.i"
	@echo "... Biomes/StarterForest.s"
	@echo "... Biomes/TremorousCaves.o"
	@echo "... Biomes/TremorousCaves.i"
	@echo "... Biomes/TremorousCaves.s"
	@echo "... Biomes/shop.o"
	@echo "... Biomes/shop.i"
	@echo "... Biomes/shop.s"
	@echo "... Player/Inventory.o"
	@echo "... Player/Inventory.i"
	@echo "... Player/Inventory.s"
	@echo "... Player/Player.o"
	@echo "... Player/Player.i"
	@echo "... Player/Player.s"
	@echo "... ScreenDisplay/src/Hotbar.o"
	@echo "... ScreenDisplay/src/Hotbar.i"
	@echo "... ScreenDisplay/src/Hotbar.s"
	@echo "... ScreenDisplay/src/ReadScreenFile.o"
	@echo "... ScreenDisplay/src/ReadScreenFile.i"
	@echo "... ScreenDisplay/src/ReadScreenFile.s"
	@echo "... ScreenDisplay/src/ScreenDisplay.o"
	@echo "... ScreenDisplay/src/ScreenDisplay.i"
	@echo "... ScreenDisplay/src/ScreenDisplay.s"
	@echo "... ScreenDisplay/test/test.o"
	@echo "... ScreenDisplay/test/test.i"
	@echo "... ScreenDisplay/test/test.s"
	@echo "... combatCMake/combatSrc/cabinspirit.o"
	@echo "... combatCMake/combatSrc/cabinspirit.i"
	@echo "... combatCMake/combatSrc/cabinspirit.s"
	@echo "... combatCMake/combatSrc/character.o"
	@echo "... combatCMake/combatSrc/character.i"
	@echo "... combatCMake/combatSrc/character.s"
	@echo "... combatCMake/combatSrc/crygolem.o"
	@echo "... combatCMake/combatSrc/crygolem.i"
	@echo "... combatCMake/combatSrc/crygolem.s"
	@echo "... combatCMake/combatSrc/darkgobshaman.o"
	@echo "... combatCMake/combatSrc/darkgobshaman.i"
	@echo "... combatCMake/combatSrc/darkgobshaman.s"
	@echo "... combatCMake/combatSrc/enemy.o"
	@echo "... combatCMake/combatSrc/enemy.i"
	@echo "... combatCMake/combatSrc/enemy.s"
	@echo "... combatCMake/combatSrc/gatekeeper.o"
	@echo "... combatCMake/combatSrc/gatekeeper.i"
	@echo "... combatCMake/combatSrc/gatekeeper.s"
	@echo "... combatCMake/combatSrc/gobgrunt.o"
	@echo "... combatCMake/combatSrc/gobgrunt.i"
	@echo "... combatCMake/combatSrc/gobgrunt.s"
	@echo "... combatCMake/combatSrc/madking.o"
	@echo "... combatCMake/combatSrc/madking.i"
	@echo "... combatCMake/combatSrc/madking.s"
	@echo "... combatCMake/combatSrc/oasisguard.o"
	@echo "... combatCMake/combatSrc/oasisguard.i"
	@echo "... combatCMake/combatSrc/oasisguard.s"
	@echo "... combatCMake/combatSrc/overbat.o"
	@echo "... combatCMake/combatSrc/overbat.i"
	@echo "... combatCMake/combatSrc/overbat.s"
	@echo "... combatCMake/combatSrc/queenspider.o"
	@echo "... combatCMake/combatSrc/queenspider.i"
	@echo "... combatCMake/combatSrc/queenspider.s"
	@echo "... combatCMake/combatSrc/sandworm.o"
	@echo "... combatCMake/combatSrc/sandworm.i"
	@echo "... combatCMake/combatSrc/sandworm.s"
	@echo "... combatCMake/combatSrc/sunkwarden.o"
	@echo "... combatCMake/combatSrc/sunkwarden.i"
	@echo "... combatCMake/combatSrc/sunkwarden.s"
	@echo "... combatCMake/combatSrc/villcultist.o"
	@echo "... combatCMake/combatSrc/villcultist.i"
	@echo "... combatCMake/combatSrc/villcultist.s"
	@echo "... test/Biome_test.o"
	@echo "... test/Biome_test.i"
	@echo "... test/Biome_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

